### ISSUE TITLE
Raising an error when an asset is not found

### ISSUE THREAD

**Issue by tiagobabo** [rails/propshaft#127] opened 2023-02-24 15:41 UTC
As per the Rails [docs](https://guides.rubyonrails.org/asset_pipeline.html#raise-an-error-when-an-asset-is-not-found), if one is using sprockets-rails >= 3.2.0 it's possible to set `config.assets.unknown_asset_fallback = false` and raise an error when an asset is not found. Looking at the [current implementation](https://github.com/rails/propshaft/blob/62476fa31b5981fdf4e026f18c5031755885e5ec/lib/propshaft/compilers/css_asset_urls.rb#L31) of `asset_url` we get a warning if propshaft is unable to resolve an asset URL. Would it be possible to have a similar configuration that would allow raising an error instead (especially on `assets:precompile`)?

**Comment by rmacklin** [comment] 2023-02-24 16:04
It's worth noting that propshaft already does raise a `MissingAssetError` for assets that aren't resolved when the asset is referenced directly in an actionview helper method like `javascript_include_tag`, etc., as seen here:
https://github.com/rails/propshaft/blob/62476fa31b5981fdf4e026f18c5031755885e5ec/lib/propshaft/helper.rb#L3-L5

The code linked in @tiagobabo's post is specific to assets that are referenced in a `url(...)` value within a CSS file, which are potentially transformed by the `CssAssetUrls` processor.

Note, however, that some expressions inside `url()` should never be transformed (e.g. an inline data-URI or an fully qualified URL to an external domain). This explains why the current implementation can be useful.

I do see the value in adding such a configuration to throw an exception rather than just logging a warning if an asset inside `url()` can't be resolved, but it seems like it would have to be restricted to only apply for expressions inside `url()` that makes sense to be transformed (e.g. relative URLs).

**Comment by tiagobabo** [comment] 2023-02-24 16:07
You're right, this only happens for assets required inside `url(...)`, thanks for clarifying that.

**Comment by brenogazzola** [comment] 2023-10-23 21:44
My original implementation was for a `raise`, but when I started migration my own app from sprockets to propshaft, I noticed that it was easier to let all errors to be logged and fix them in batches than doing the crash-fix-reload-crash-fix-reload cycle.

Is there a reason why raising would be better? I'm asking because between our two experiences we might figure out a third option that might be better than logging/raising

**Comment by brenogazzola** [comment] 2023-11-03 01:11
I’ll close this issue for now as it’s not a bug but a feature request, and from my experience logging provides a better workflow than raising. If anyone has further input, feel free to comment.

**Closed by brenogazzola** 2023-11-03 01:11 UTC
