### ISSUE TITLE
Support for .erb files

### ISSUE THREAD

**Issue by j-manu** [rails/propshaft#109] opened 2022-09-08 17:36 UTC
In sprockets if you place `assets/javascript/client/pay.html.erb`  and `assets/javascript/client/pay.js.erb` both will be compiled and placed in assets folder as `client/pay.html` and `client/pay.js` . Is there a way to replicate this behaviour in propshaft?

**Comment by brenogazzola** [comment] 2022-09-08 18:42
Unfortunately no. Propshaft by design does not do transpiling/compiling (coffee to js, scss to css, etc). You need extra gems like cssbundling-rails and jsbundling-rails for that. Currently I’m not aware of any gems that handle erb files.

**Comment by brenogazzola** [comment] 2022-09-08 18:42
Feel free to keep comenting, but I’m closing this since it is not an issue.

**Closed by brenogazzola** 2022-09-08 18:42 UTC
